---
- hosts: localhost
  user: admin
  sudo: yes
  sudo_user: root
  vars_files:
    - ../vars/secret
    - ../group_vars/ssh_banned_users.yml

  tasks:
  - name: create key directory
    action: file path=/opt/ssh/authorized_keys state=directory
      owner=0 group=0 mode=0755

  - name: upload user key
    action: copy src=/opt/ansible_playbooks/keys/{{ item.name }}
      dest=/opt/ssh/authorized_keys
      owner=0 group=0 mode=644
    with_items: sshusers

  - name: Remove ssh user keys
    authorized_key: user=admin key="{{ lookup('file', '/opt/ansible_playbooks/user_keys/'+item.name) }}" state=absent
    with_items: sshusers
    notify:
    - restart ssh

  handlers:
    - name: restart ssh
      service: name=ssh state=restarted