---
 - hosts: wombats
   remote_user: pg1712
   sudo: yes

   tasks:
   
   - name: Making /Boot space
     shell: sudo dpkg -P linux-image-3.2.0-{70,71,72,73,74,75,76,77,78,79}-generic executable=/bin/bash 
   
   - name: Fixing Wombal Boot dir issue
     shell: sudo dpkg --configure -a --force-all && sudo apt-get clean && sudo apt-get update && sudo apt-get install -f -y && sudo apt-get autoremove -y executable=/bin/bash 
  
   - name: Install add-apt-repostory
     apt: name=software-properties-common state=latest

   - name: Add Oracle Java Repository
     apt_repository: repo='ppa:webupd8team/java'

   - name: Accept Java 8 Licence
     shell: echo oracle-java8-installer shared/accepted-oracle-license-v1-1 select true | tee /etc/oracle-java-8-licence-acceptance | /usr/bin/debconf-set-selections
     args:
      creates: /etc/oracle-java-8-licence-acceptance

   - name: Install Oracle Java 8
     apt: name={{item}} state=latest force=yes dpkg_options='force-confold'
     with_items:
      - oracle-java8-installer
      - ca-certificates
      - oracle-java8-set-default
