---
- hosts: amazon
  user: admin
  sudo: yes
  sudo_user: root
  vars_files:
    - secret
  vars:
    - user_password: ***REMOVED***
  tasks:
    # Add the admin user with a bash shell, appending the group 'admin' and 'sudo' to the user's groups password={{user_password}}
  - name: Creating user "{{ uusername }}" with admin access
    user: name=admin shell=/bin/bash groups=admin,sudo append=yes home=/home/admin createhome=yes state=present
  
  - name: Installing  Git...
    apt: name=git update_cache=yes state=present
    
  - name: Installing cmake...
    apt: name=cmake state=present
    
  - name: Installing python-pip ....
    apt: name=python-pip state=present
    
  - shell: sudo apt-get update; sudo pip install -U pip setuptools wheel virtualenv; echo 'DONE'
  
  - name: Installing libffi-dev..
    apt: name=libffi-dev state=present
 
  - name: Installing libmysqlclient-dev...
    apt: name=libmysqlclient-dev state=present
    
  - name: Installing python-dev..
    apt: name=python-dev state=present

  - name: Installing libevent-dev...
    apt: name=libevent-dev state=present

  - name: Installing  libxslt1-dev...
    apt: name=libxslt1-dev state=present

  - name: Installing libxml2-dev...
    apt: name=libxml2-dev state=present
    
  - name: Installing python-pyside..
    apt: name=python-pyside state=present
 
  - name: Installing libssl-dev...
    apt: name=libssl-dev state=present
    
    
   