---
- hosts: amazon
  user: admin
  sudo: yes
  sudo_user: root
  vars_files:
    - secret
  tasks:
  
  - name: Installing   ...
    apt: name=git update_cache=yes state=present
    
  - name: Installing python-pip ....
    apt: name=python-pip state=present
    
  - shell: sudo apt-get update; sudo pip install -U pip setuptools wheel virtualenv; echo 'DONE'
  
  - name: Installing libffi-dev..
    apt: name=libffi-dev state=present
 
  - name: Installing libmysqlclient-dev...
    apt: name=libmysqlclient-dev state=present
    
    