---
- hosts: databases
  user: admin
  sudo: yes
  sudo_user: root
  vars_files:
    - secret
  tasks:
  - name: Updating local Semaphore Repository
    local_action: git repo=git@bitbucket.org:***REMOVED***/***REMOVED***-build-tools.git
          dest=/opt/***REMOVED***-build-tools
          force=yes
          clone=yes
          accept_hostkey=yes
          key_file=/home/admin/ansible_playbooks/keys/id_rsa
  - file: path='/home/admin/ansible_playbooks' state=directory mode=0755
  - file: path='/home/admin/ansible_playbooks/keys' state=directory mode=0755
  - name: Copying Public key
    copy: src='/home/admin/ansible_playbooks/keys-store/id_rsa.pub' dest='/home/admin/ansible_playbooks/keys/id_rsa.pub'
          force=yes
          backup=yes
          owner=admin
          group=admin
          mode=0644
  - name: Copyign Private key
    copy: src=/home/admin/ansible_playbooks/keys-store/id_rsa dest=/home/admin/ansible_playbooks/keys/id_rsa
          force=yes
          backup=yes
          owner=admin
          group=admin
          mode=0600
  - name: Installing Git 
    # Update repositories cache and install "Git" package
    apt: name=git update_cache=yes state=present
  - name: Setup the Git repo
    git: repo=git@bitbucket.org:***REMOVED***/***REMOVED***-build-tools.git
          dest=/opt/***REMOVED***-build-tools
          force=yes
          clone=yes
          accept_hostkey=yes
          key_file=/home/admin/ansible_playbooks/keys/id_rsa
  - file: src=/opt/***REMOVED***-build-tools/***REMOVED***/launcher.sh dest=/usr/bin/***REMOVED***-launcher.sh
          owner=root
          group=root
          state=link
