---
  # Playbook file "playbooks/rabbitmq/rabbitMQ-install.yml"
  # Empty play that only gather facts once and set required variables.
     
  # Play to setup RabbitMQ role
  - name: Rabbit Nodes
    hosts: rabbit-prod
    gather_facts: yes
    user: ansible
    become: yes
    become_method: sudo
    vars_files:
      - ../../vars/secret
    
    roles:
       - { role: '../ansible-rabbitmq'}
