---
- hosts: go-deploy
  user: admin
  sudo: yes
  sudo_user: root
  vars_files:
    - ../vars/secret
    - ../vars/main.yml
    - ../defaults/main.yml

  tasks:
     
  - name: Setup up /opt/go Path
    file: path=/opt/go/src/bitbucket.org/***REMOVED*** state=directory owner=admin group=admin mode=0775
    file: path=/opt/go/bin state=directory owner=admin group=admin mode=0775
    file: path=/opt/go/pkg state=directory owner=admin group=admin mode=0775
    
#  - name: ensure github is a known host
#    action: sshknownhosts host=bitbucket.org state=present 

    #Project PATHS
  - name: Setup the enetsports Git repo
    git: repo=git@bitbucket.org:***REMOVED***/go-enetsports.git
          dest=/opt/go/src/bitbucket.org/***REMOVED***/go-enetsports
          force=yes
          clone=yes
          accept_hostkey=yes
          key_file=/home/admin/.ansible_playbooks/keys/id_rsa
          
    # Install Go lang dependencies and fix path
  - name: Download the Go tarball
    get_url: url={{ go_download_location }}
           dest=/usr/local/src/{{ go_tarball }}
           sha256sum={{ go_tarball_checksum }}

  - name: Register the current Go version (if any)
    command: /usr/local/go/bin/go version
    ignore_errors: yes
    register: go_version
    changed_when: false

  - name: Extract the Go tarball if Go is not yet installed or if it is not the desired version
    command: tar -C /usr/local -xf /usr/local/src/{{ go_tarball }}
    when: go_version|failed or go_version.stdout != go_version_target

    #Configuring Path variables
  - name: Add the Go bin directory to the PATH environment variable for all users
    copy: src=../files/go-bin.sh
          dest=/etc/profile.d
  - name: Set GOPATH for all users
    copy: src=../files/go-path.sh
          dest=/etc/profile.d
  - name: Set API env variable for all users
    copy: src=../files/go-api.sh
          dest=/etc/profile.d
    
    #Executable PATHS
  - action: shell date '+%F.%H:%M:%S' 
    register: mydate 
  - action: file dest=/opt/go/bin/{{ mydate.stdout }}  state=directory 
                              
    # Create go-executables -- GO env dependencies were needed
  - name: Executing go-get under go-enetsports Parser
    shell: source /etc/profile.d/go-api.sh && source /etc/profile.d/go-path.sh && source /etc/profile.d/go-bin.sh && cd /opt/go/src/bitbucket.org/***REMOVED***/go-enetsports/Parser/ && go get executable=/bin/bash
  - name: Executing go-install under go-enetsports Parser
    shell: source /etc/profile.d/go-api.sh && source /etc/profile.d/go-path.sh && source /etc/profile.d/go-bin.sh && cd /opt/go/src/bitbucket.org/***REMOVED***/go-enetsports/Parser/ && go install executable=/bin/bash
  - name: Building go-execution under go-enetsports Parser
    shell: source /etc/profile.d/go-api.sh && source /etc/profile.d/go-path.sh && source /etc/profile.d/go-bin.sh && cd /opt/go/src/bitbucket.org/***REMOVED***/go-enetsports/Parser/ && go build executable=/bin/bash
- name: Executing go-get under go-enetsports Server
    shell: source /etc/profile.d/go-api.sh && source /etc/profile.d/go-path.sh && source /etc/profile.d/go-bin.sh && cd /opt/go/src/bitbucket.org/***REMOVED***/go-enetsports/Server/ && go get executable$
  - name: Executing go-install under go-enetsports Server
    shell: source /etc/profile.d/go-api.sh && source /etc/profile.d/go-path.sh && source /etc/profile.d/go-bin.sh && cd /opt/go/src/bitbucket.org/***REMOVED***/go-enetsports/Server/ && go install execut$
  - name: Building go-execution under go-enetsports Server
    shell: source /etc/profile.d/go-api.sh && source /etc/profile.d/go-path.sh && source /etc/profile.d/go-bin.sh && cd /opt/go/src/bitbucket.org/***REMOVED***/go-enetsports/Server/ && go build executab$

    
    # Creating build Executables - Moving to correct folder
  - name: Moving ***REMOVED***-goenet-parser under /opt/go/bin/{{ mydate.stdout }}
    copy: src=/opt/go/src/bitbucket.org/***REMOVED***/trading-system-framework/go-enetsports/Parser/Parser
          dest=/opt/go/bin/{{ mydate.stdout }}/***REMOVED***-goenet-parser
          mode="u=rwx,g=rwx,o=rwx"
  - name: Moving ***REMOVED***-goenet-server under /opt/go/bin/{{ mydate.stdout }}
    copy: src=/opt/go/src/bitbucket.org/***REMOVED***/trading-system-framework/go-enetsports/Server/Server
          dest=/opt/go/bin/{{ mydate.stdout }}/***REMOVED***-goenet-server
          mode="u=rwx,g=rwx,o=rwx"

    
    # Creating symbolic links for easy access
  - name: Creating new symbolic links
    command: ls -al
  - file: src=/opt/go/bin/{{ mydate.stdout }}/***REMOVED***-goenet-parser dest=/usr/bin/***REMOVED***-goenet-parser-pre
          owner=root
          group=root
          state=link
  - file: src=/opt/go/bin/{{ mydate.stdout }}/***REMOVED***-goenet-server dest=/usr/bin/***REMOVED***-goenet-server-pre
          owner=root
          group=root
          state=link
