---
- hosts: stratabet-web
  user: ansible
  sudo: yes
  sudo_user: root
  vars:
    node_env: "{{ DEPLOY_ENV|default('staging') }}"
    branch_env: "{{ BRANCH|default('master') }}" 
  vars_files:
    - ../vars/secret
    - ../vars/main.yml
    - ../defaults/main.yml

  tasks:
     
  - name: Setup up /opt/go Path
    file: path=/opt/go/src/bitbucket.org/***REMOVED*** state=directory owner=admin group=admin mode=0775
    file: path=/opt/go/bin state=directory owner=admin group=admin mode=0775
    file: path=/opt/go/pkg state=directory owner=admin group=admin mode=0775
    
#  - name: ensure github is a known host
#    action: sshknownhosts host=bitbucket.org state=present 

    #Project PATHS
  - name: Setup the trading-system-framework Git repo
    git: repo=git@bitbucket.org:***REMOVED***/trading-system-framework.git
          dest=/opt/go/src/bitbucket.org/***REMOVED***/trading-system-framework
          force=yes
          clone=yes
          accept_hostkey=yes
          key_file=/home/admin/.ansible_playbooks/keys/id_rsa    
  - name: Setup the data-api dependency Git repo
    git: repo=git@bitbucket.org:***REMOVED***/data_api.git
          dest=/opt/go/src/bitbucket.org/***REMOVED***/data_api
          force=yes
          clone=yes
          version={{branch_env}}
          accept_hostkey=yes
          key_file=/home/admin/.ansible_playbooks/keys/id_rsa
  - name: Setup the advantedj-api Git repo
    git: repo=git@bitbucket.org:***REMOVED***/advantedj_api.git
         dest=/opt/go/src/bitbucket.org/***REMOVED***/advantedj_api
         force=yes
         clone=yes
         version={{branch_env}}
         accept_hostkey=yes
         key_file=/home/admin/.ansible_playbooks/keys/id_rsa
  - name: Setup the Stratabet Git repo
    git: repo=git@bitbucket.org:***REMOVED***/stratabet.git
         dest=/opt/stratabet
         force=yes
         clone=yes
         version={{branch_env}}
         accept_hostkey=yes
         key_file=/home/admin/.ansible_playbooks/keys/id_rsa     
        
         
    # Install Go lang dependencies and fix path
  - name: Download the Go tarball
    get_url: url={{ go_download_location }}
           dest=/usr/local/src/{{ go_tarball }}
           sha256sum={{ go_tarball_checksum }}

  - name: Register the current Go version (if any)
    command: /usr/local/go/bin/go version
    ignore_errors: yes
    register: go_version
    changed_when: false

  - name: Extract the Go tarball if Go is not yet installed or if it is not the desired version
    command: tar -C /usr/local -xf /usr/local/src/{{ go_tarball }}
    when: go_version|failed or go_version.stdout != go_version_target

    #Configuring Path variables
  - name: Add the Go bin directory to the PATH environment variable for all users
    copy: src=../files/go-bin.sh
          dest=/etc/profile.d
  - name: Set GOPATH for all users
    copy: src=../files/go-path.sh
          dest=/etc/profile.d
  - name: Set API env variable for all users
    copy: src=../files/go-api.sh
          dest=/etc/profile.d
    
    #Executable PATHS
  - action: shell date '+%F.%H:%M:%S' 
    register: mydate 
  - action: file dest=/opt/go/bin/{{ mydate.stdout }}  state=directory 
                              
    # Create go-executables -- GO env dependencies were needed
  - name: Executing go-get under data_api
    shell: source /etc/profile.d/go-api.sh && source /etc/profile.d/go-path.sh && source /etc/profile.d/go-bin.sh && cd /opt/go/src/bitbucket.org/***REMOVED***/data_api/ && go get executable=/bin/bash
  - name: Building go-data-api under data_api
    shell: source /etc/profile.d/go-api.sh && source /etc/profile.d/go-path.sh && source /etc/profile.d/go-bin.sh && cd /opt/go/src/bitbucket.org/***REMOVED***/data_api/ && go build executable=/bin/bash
  - name: Executing go-get under advantedj_api
    shell: source /etc/profile.d/go-api.sh && source /etc/profile.d/go-path.sh && source /etc/profile.d/go-bin.sh && cd /opt/go/src/bitbucket.org/***REMOVED***/advantedj_api/ && go get executable=/bin/bash
  - name: Building advantedj_api
    shell: source /etc/profile.d/go-api.sh && source /etc/profile.d/go-path.sh && source /etc/profile.d/go-bin.sh && cd /opt/go/src/bitbucket.org/***REMOVED***/advantedj_api/ && go build executable=/bin/bash
  - name: Building advantedj_api onboarding runner 
    shell: source /etc/profile.d/go-api.sh && source /etc/profile.d/go-path.sh && source /etc/profile.d/go-bin.sh && cd /opt/go/src/bitbucket.org/***REMOVED***/advantedj_api/runners/onboarding && go build executable=/bin/bash    
  - name: Building advantedj_api lineup comparison runner 
    shell: source /etc/profile.d/go-api.sh && source /etc/profile.d/go-path.sh && source /etc/profile.d/go-bin.sh && cd /opt/go/src/bitbucket.org/***REMOVED***/advantedj_api/runners/lineup && go build executable=/bin/bash    
    notify:
    - test all
    
    # Creating build Executables - Moving to correct folder
  - name: Moving ***REMOVED***-data_api under /opt/go/bin/'{{ mydate }}'
    copy: src=/opt/go/src/bitbucket.org/***REMOVED***/data_api/data_api
          dest=/opt/go/bin/{{ mydate.stdout }}/***REMOVED***-data_api
          mode="u=rwx,g=rwx,o=rwx"
  - name: Moving ***REMOVED***-advantedj_api under /opt/go/bin/'{{ mydate }}'
    copy: src=/opt/go/src/bitbucket.org/***REMOVED***/advantedj_api/advantedj_api
          dest=/opt/go/bin/{{ mydate.stdout }}/***REMOVED***-advantedj_api
          mode="u=rwx,g=rwx,o=rwx"   
  - name: Moving ***REMOVED***-advantedj_api-onboarding under /opt/go/bin/'{{ mydate }}'
    copy: src=/opt/go/src/bitbucket.org/***REMOVED***/advantedj_api/runners/onboarding/onboarding
          dest=/opt/go/bin/{{ mydate.stdout }}/***REMOVED***-onboarding
          mode="u=rwx,g=rwx,o=rwx"
  - name: Moving ***REMOVED***-advantedj_api-lineup under /opt/go/bin/'{{ mydate }}'
    copy: src=/opt/go/src/bitbucket.org/***REMOVED***/advantedj_api/runners/lineup/lineup
          dest=/opt/go/bin/{{ mydate.stdout }}/***REMOVED***-lineup
          mode="u=rwx,g=rwx,o=rwx"
    
    # Creating symbolic links for easy access
  - name: Creating new symbolic links
    command: ls -al
  - file: src=/opt/go/bin/{{ mydate.stdout }}/***REMOVED***-advantedj_api dest=/usr/bin/***REMOVED***-advantedj_api-pre
          owner=root
          group=root
          state=link
  - file: src=/opt/go/bin/{{ mydate.stdout }}/***REMOVED***-data_api dest=/usr/bin/***REMOVED***-data_api-pre
          owner=root
          group=root
          state=link
  - file: src=/opt/go/bin/{{ mydate.stdout }}/***REMOVED***-onboarding dest=/usr/bin/***REMOVED***-onboarding-pre
          owner=root
          group=root
          state=link
  - file: src=/opt/go/bin/{{ mydate.stdout }}/***REMOVED***-lineup dest=/usr/bin/***REMOVED***-lineup-pre
          owner=root
          group=root
          state=link
          
    ##
    # Apt package installation of required software.
    ##
  - name: General | Install required packages.
    apt: pkg={{item}} state=installed
    with_items:
     - npm
     - curl
    
    ## 
    # Stratabet Web dependencies
    ##
    #- name: Executing npm install Bower and Gulp under stratabet
    #  shell: cd /opt/stratabet/ && npm cache clean -f && npm install -g n && sudo n stable executable=/bin/bash    
    #- name: Executing npm install Bower and Gulp under stratabet
    #  shell: cd /opt/stratabet/ && npm install -g bower && npm install -g gulp executable=/bin/bash
  - name: Executing npm Install under stratabet
    shell: cd /opt/stratabet/ && npm install && bower install --allow-root executable=/bin/bash
  - command: echo "Going to build statabet in '{{ node_env }}' mode!!!"
  - name: Build Stratabet in Prod mode
    shell: cd /opt/stratabet/ && gulp build:prod && sed -i.orig 's|http://localhost:5555|https://api.stratabet.com|' public/index.html && sed -i.orig2 's|--applicationMode--|production|' public/index.html && sed -i.orig3 's|pk_test_RG0dNH0QAzOsFnTuRVvVhB9Y|pk_live_n9ZbWR9pWtRfh6b1Xn9iRAk0|' public/index.html executable=/bin/bash  
    when: node_env == "production"
  - name: Build Stratabet in Staging mode
    shell: cd /opt/stratabet/ && gulp build:prod && sed -i.orig 's|http://localhost:5555|https://api-staging.stratabet.com|' public/index.html 
    when: node_env == "staging"
    
  # Manage Supervisor stratabet task - restart them in a specific order
  - name: Restart Data API supervisor Job
    supervisorctl: name="stratabet:data_api" state=restarted
  - name: Restart Advantadj API supervisor Job
    supervisorctl: name="stratabet:advantedj_api" state=restarted
    
  handlers:
   - name: test all
     shell: source /etc/profile.d/go-api.sh && source /etc/profile.d/go-path.sh && source /etc/profile.d/go-bin.sh && cd /opt/go/src/bitbucket.org/***REMOVED***/data_api && go test . ./... executable=/bin/bash
     shell: source /etc/profile.d/go-api.sh && source /etc/profile.d/go-path.sh && source /etc/profile.d/go-bin.sh && cd /opt/go/src/bitbucket.org/***REMOVED***/advantedj_api && go test . ./... executable=/bin/bash
     
     
