---
- hosts: all
  user: ansible
  become: yes
  become_method: sudo
  vars_files:
    - ../../vars/secret
    - ../../defaults/main.yml

  tasks:
    - name: Installing Sendmail package (APT)
      apt: pkg=sendmail state=present

    - name: Installing Mailutils package (APT)
      apt: pkg=mailutils state=present
      
    - name: Installing SSMTP package (APT)
      apt: pkg=ssmtp state=present

    - name: Configuring SSMTP
      template: src=../../templates/ssmtp-default.j2 dest=/etc/ssmtp/ssmtp.conf
      
    - name: Kill all running Sendmail instances
      shell: sudo killall sendmail executable=/bin/bash  
      ignore_errors: True
      
    - file: src=/usr/sbin/ssmtp dest=/usr/sbin/sendmail
          owner=root
          group=root
          state=link
          force=yes