---
- hosts: all
  user: ansible
  become: yes
  become_method: sudo
  vars_files:
    - ../../vars/secret
    - ../../defaults/main.yml

  tasks:
    - name: Installing SMTP packages (APT)
      apt: pkg=sendmail state=present
      apt: pkg=mailutils state=present
      apt: pkg=ssmtp state=present

    - name: Configuring SSMTP
      template: src=../../templates/ssmtp-default.j2 dest=/etc/ssmtp/ssmtp.conf
      
    - name: Replace sendmail
      shell: sudo killall sendmail executable=/bin/bash 
      shell: sudo rm -rf /usr/sbin/sendmail
      
    - file: src=/usr/sbin/ssmtp dest=/usr/sbin/sendmail
          owner=root
          group=root
          state=link
          force=yes