---
- hosts: all
  user: ansible
  become: yes
  become_method: sudo
  vars_files:
    - ../../vars/secret
    - ../../defaults/main.yml

  tasks:
  - name: Set timezone variable to UTC
    copy: content='Etc/UTC'
          dest=/etc/timezone
           owner=root
           group=root
           mode=0644
           backup=yes
    notify:
      - update timezone


  handlers:
    - name: update timezone
      command: dpkg-reconfigure --frontend noninteractive tzdata