---
- hosts: localhost
  user: admin
  sudo: yes
  sudo_user: root
  vars_files:
    - ../vars/secret
    - ../group_vars/ssh_users.yml

  tasks:
  - name: create key directory
    action: file path=/opt/ssh/authorized_keys state=directory
      owner=0 group=0 mode=0755

  - name: upload user key
    action: copy src=/opt/ansible_playbooks/keys/{{ item.name }}
      dest=/opt/ssh/authorized_keys
      owner=0 group=0 mode=644
    with_items: sshusers

  - name: Add ssh user keys
    path_var: /opt/ansible_playbooks/keys/{{ item.name }}
    authorized_key: user=admin key="{{ lookup('file', 'path_var') }}"
    with_items: sshusers
    notify:
    - restart sshd

  handlers:
    - name: restart sshd
      service: name=sshd state=restarted