---
- name: Restarting ufw
  service: name=ufw
           state=restarted
           
- name: Reloading ufw
  command: ufw reload
  
- name: Restarting fail2ban
  service: name=fail2ban state=restarted