---
- name: restart ufw
  service: name=ufw
           state=restarted
           
- name: reload ufw
  command: ufw reload
  
- name: restart fail2ban
  service: name=fail2ban state=restarted
  
- name: restart ssh
  service: name=ssh state=restarted