---

rabbitmq_use_upstream_repository: true
rabbitmq_erlang_cookie: OZJCOGOWJOZILOYREDWL
rabbitmq_ulimit_open_files: 65000
rabbitmq_create_cluster: yes
rabbitmq_cluster_master: math02
rabbitmq_use_longname: 'false'
rabbitmq_vhosts: [dev]
rabbitmq_ha_enabled: yes
rabbitmq_ha_pattern: '.*'
rabbitmq_ha_mode: 'all'

rabbitmq_ssl: no
rabbitmq_ssl_port: 5671
rabbitmq_ssl_use_snakeoil_cert: yes
rabbitmq_ssl_ca_cert:
rabbitmq_ssl_cert:
rabbitmq_ssl_key:
# Custom option: igore (default), autoheal, pause-minority, pause-if-all-down
rabbitmq_cluster_partition_handling: autoheal

rabbitmq_plugins:
  - rabbitmq_management

rabbitmq_users:
  - user: admin
    password: ***REMOVED***
    vhost: /
    configure_priv: .*
    read_priv: .*
    write_priv: .*
    tags: administrator

  - user: pythondev
    password: pythondev777
    vhost: dev
    configure_priv: .*
    read_priv: .*
    write_priv: .*
    tags: administrator

  - user: golangdev
    password: golangdev888
    vhost: dev
    configure_priv: .*
    read_priv: .*
    write_priv: .*
    tags: administrator

rabbitmq_users_removed:
  - guest

